-- Generated by nwg-displays on 2026-07-15 at 17:54:10. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "800x600@60.02",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10
})
