export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="mps" # set by `omz`
CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13
# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"
# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"
# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"
# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
#COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(git
	zsh-autosuggestions
	zsh-syntax-highlighting)

ZSH_DISABLE_COMPFIX="true"
source $ZSH/oh-my-zsh.sh
alias cat="bat --theme=gruvbox-dark"
alias ls="lsd -F"
alias alacritty="alacritty & disown"
alias life="glow ~/life/"
alias kitty="LIBGL_ALWAYS_SOFTWARE=1 kitty"
alias icat="kitty +kitten icat"
alias info="cd $HOME/Ing\ Informatica/7to.\ Sem"
alias proy="cd $HOME/Proyectos"
alias e=$EDITOR
alias vi="$EDITOR"
declare -x EDITOR=nvim
## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /home/mmppppss/.dart-cli-completion/zsh-config.zsh ]] && . /home/mmppppss/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]


# pnpm
export PNPM_HOME="/home/mps/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
